## 实现自动化派单处理

In [19]:
import paramiko
hostname='120.132.50.245'
port=22
username='app'
pkey='C:/Users/jbymsolo/.ssh/id_rsa'
key=paramiko.RSAKey.from_private_key_file(pkey)
s=paramiko.SSHClient()
s.load_system_host_keys()
s.connect(hostname,port,username,pkey=key)
stdin,stdout,stderr=s.exec_command("mysql -h10.10.135.131 -udwms -p25d48b52698a7f2@FORdwms? -Dmysql -e 
                                   'select supplier_receiver_distance,transporter_supplier_distance,today_finish_order_num,transporter_before_fourteen_day_paidan_lv,
        paidan_receiver_distance_jiedan_receiver_min,
        paidan_supplier_distance_jiedan_receiver_min,
        paidan_hour,
        transporter_before_seven_day_paidan_lv,
        paidan_supplier_distance_jiedan_receiver_max,
        paidan_receiver_distance_jiedan_receiver_max,
        allowance_amt,label from dw_test.bian_paidan_model_data limit 10'")
data = stdout.readlines()
for index,value in enumerate(data):
    data[index] = value.split()

In [50]:
import pandas as pd

def data_process(data)
    data = pd.DataFrame(data)
    paidan_data = paidan_data.fillna(value = 0)
    paidan_data.loc[paidan_data.paidan_receiver_distance_jiedan_receiver_max > 10000,"paidan_receiver_distance_jiedan_receiver_max"] = paidan_data["paidan_receiver_distance_jiedan_receiver_max"][paidan_data.paidan_receiver_distance_jiedan_receiver_max < 10000].mean()
    paidan_data.loc[paidan_data.paidan_receiver_distance_jiedan_receiver_min > 10000,"paidan_receiver_distance_jiedan_receiver_min"] = paidan_data["paidan_receiver_distance_jiedan_receiver_min"][paidan_data.paidan_receiver_distance_jiedan_receiver_min < 10000].mean()
    paidan_data.loc[paidan_data.paidan_supplier_distance_jiedan_receiver_max > 10000,"paidan_supplier_distance_jiedan_receiver_max"] = paidan_data["paidan_supplier_distance_jiedan_receiver_max"][paidan_data.paidan_supplier_distance_jiedan_receiver_max < 10000].mean()
    paidan_data.loc[paidan_data.paidan_supplier_distance_jiedan_receiver_min > 10000,"paidan_supplier_distance_jiedan_receiver_min"] = paidan_data["paidan_supplier_distance_jiedan_receiver_min"][paidan_data.paidan_supplier_distance_jiedan_receiver_min < 10000].mean()
    paidan_data.loc[paidan_data.supplier_receiver_distance > 10000,"supplier_receiver_distance"] = paidan_data["supplier_receiver_distance"][paidan_data.supplier_receiver_distance < 10000].mean()
    paidan_data.loc[paidan_data.transporter_supplier_distance > 10000,"transporter_supplier_distance"] = paidan_data["transporter_supplier_distance"][paidan_data.transporter_supplier_distance < 10000].mean()

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,create_dt,order_supplier_transporter,paidan_hour,order_source_from,is_cargo_advance_needed,tips_amt,allowance_amt,deliver_fee_amt,fee_sum,transporter_before_one_day_paidan_num,...,supplier_receiver_distance,paidan_supplier_distance_jiedan_receiver_min,paidan_supplier_distance_jiedan_receiver_max,paidan_receiver_distance_jiedan_receiver_min,paidan_receiver_distance_jiedan_receiver_max,paidan_supplier_distance_jiedan_supplier_min,paidan_supplier_distance_jiedan_supplier_max,paidan_receiver_distance_jiedan_supplier_min,paidan_receiver_distance_jiedan_supplier_max,label
1,2015-12-09,121775086_-99_114228_350084,22,0,1,0.00,4.00,5.00,9.00,18,...,1881.1614949385228,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1
2,2015-12-09,121775085_-99_20512_46174,22,0,1,0.00,4.00,3.00,7.00,12,...,1555.0536843169052,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,-1
3,2015-12-09,121775084_-99_102088_230126,22,0,0,0.00,4.00,2.00,6.00,3,...,577.8560631185424,333.38946816922254,499.3504075474554,279.08626836321366,419.0980595290775,0,0,577.8560631185424,577.8560631185424,1
4,2015-12-09,121775071_-99_157479_571724,22,0,1,0.00,4.00,3.00,7.00,38,...,678.7305644769166,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,-1
5,2015-12-09,121774645_-99_109315_667818,22,0,0,0.00,4.00,3.00,7.00,10,...,810.7300341457938,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,-1
6,2015-12-09,121774734_-99_102088_493572,22,0,0,0.00,4.00,2.00,6.00,21,...,221.8099375986483,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,-1
7,2015-12-09,121775014_-99_8762_347766,22,0,0,0.00,4.00,2.00,6.00,5,...,665.2395224366234,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1
8,2015-12-09,121774969_-99_151233_593452,22,0,1,0.00,4.00,3.00,7.00,3,...,1075.9801281418347,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1
9,2015-12-09,121774962_-99_176066_662638,22,1,0,0.00,0.00,4.00,4.00,0,...,2080.261227108009,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,-1
10,2015-12-09,121774951_-99_102088_230126,22,0,0,0.00,4.00,2.00,6.00,3,...,499.3504075474554,333.38946816922254,333.38946816922254,254.84677751240054,254.84677751240054,0,0,499.3504075474554,499.3504075474554,1

In [52]:
def data_process(data):
    paidan_data = pd.DataFrame(data)
    paidan_data = paidan_data.fillna(value = 0)
    paidan_data.loc[paidan_data.paidan_receiver_distance_jiedan_receiver_max > 10000,"paidan_receiver_distance_jiedan_receiver_max"] = paidan_data["paidan_receiver_distance_jiedan_receiver_max"][paidan_data.paidan_receiver_distance_jiedan_receiver_max < 10000].mean()
    paidan_data.loc[paidan_data.paidan_receiver_distance_jiedan_receiver_min > 10000,"paidan_receiver_distance_jiedan_receiver_min"] = paidan_data["paidan_receiver_distance_jiedan_receiver_min"][paidan_data.paidan_receiver_distance_jiedan_receiver_min < 10000].mean()
    paidan_data.loc[paidan_data.paidan_supplier_distance_jiedan_receiver_max > 10000,"paidan_supplier_distance_jiedan_receiver_max"] = paidan_data["paidan_supplier_distance_jiedan_receiver_max"][paidan_data.paidan_supplier_distance_jiedan_receiver_max < 10000].mean()
    paidan_data.loc[paidan_data.paidan_supplier_distance_jiedan_receiver_min > 10000,"paidan_supplier_distance_jiedan_receiver_min"] = paidan_data["paidan_supplier_distance_jiedan_receiver_min"][paidan_data.paidan_supplier_distance_jiedan_receiver_min < 10000].mean()
    paidan_data.loc[paidan_data.supplier_receiver_distance > 10000,"supplier_receiver_distance"] = paidan_data["supplier_receiver_distance"][paidan_data.supplier_receiver_distance < 10000].mean()
    paidan_data.loc[paidan_data.transporter_supplier_distance > 10000,"transporter_supplier_distance"] = paidan_data["transporter_supplier_distance"][paidan_data.transporter_supplier_distance < 10000].mean()
    x = paidan_data.ix[:,:-1]
    y = paidan_data.ix[:,-1]
    return x,y